apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: {{ .Values.namespace }}
  labels: { app: prometheus }
spec:
  replicas: 1
  selector: { matchLabels: { app: prometheus } }
  template:
    metadata:
      labels: { app: prometheus }
    spec:
      serviceAccountName: prometheus
      securityContext: { fsGroup: 65534, runAsUser: 65534, runAsNonRoot: true }
      containers:
        - name: prometheus
          image: {{ .Values.prometheus.image }}
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus
            - --storage.tsdb.retention.time=2h # Very short retention since we only remote_write
            - --web.enable-lifecycle
          ports: [{ containerPort: 9090, name: web }]
          resources:
{{ toYaml .Values.prometheus.resources | indent 12 }}
          readinessProbe:
            httpGet: { path: /-/ready, port: web }
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - { name: config, mountPath: /etc/prometheus }
            - { name: data,   mountPath: /prometheus }
      volumes:
        - name: config
          configMap:
            name: prometheus-config
        - name: data
          emptyDir: {}
