apiVersion: v1
kind: Config
clusters:
- name: "rancher"
  cluster:
    server: "https://k8s.inova.lk"
- name: "local"
  cluster:
    server: "https://k8s.inova.lk/k8s/clusters/local"

users:
- name: "rancher"
  user:
    token: "ext/token-htbqz:c2k7zgnmnsnxstsgxpvs6cmt2m9ppw58n8v68g9v25ghb6jvjl7jtb"

contexts:
- name: "rancher"
  context:
    user: "rancher"
    cluster: "rancher"
- name: "local"
  context:
    user: "rancher"
    cluster: "local"

current-context: "local"
