from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field

from .domain import TimeWindow


class Intent(str, Enum):
    INCIDENT_INVESTIGATION = "incident_investigation"
    HEALTH_CHECK = "health_check"
    PERFORMANCE_REVIEW = "performance_review"
    HISTORICAL_QUERY = "historical_query"


# Which evidence each intent needs. Derived from the intent by lookup rather than
# generated by the model: there is no judgement here worth spending a token on.
INTENT_TOOLS: dict[Intent, list[str]] = {
    Intent.INCIDENT_INVESTIGATION: ["logs", "events", "metrics"],
    Intent.HEALTH_CHECK: ["logs", "events", "metrics"],
    Intent.PERFORMANCE_REVIEW: ["logs", "metrics"],
    Intent.HISTORICAL_QUERY: ["logs", "events"],
}

# Durations the orchestrator is allowed to choose. Free-form durations invite
# the model to emit things like "last Tuesday" that no query can use.
ALLOWED_DURATIONS = ["15m", "30m", "1h", "3h", "6h", "12h", "24h", "3d", "7d"]

DEFAULT_DURATION_BY_INTENT: dict[Intent, str] = {
    Intent.INCIDENT_INVESTIGATION: "1h",
    Intent.HEALTH_CHECK: "30m",
    Intent.PERFORMANCE_REVIEW: "3h",
    Intent.HISTORICAL_QUERY: "24h",
}


class InvestigationRequest(BaseModel):
    system_id: str
    environment: str
    question: str
    # Optional override; when set the orchestrator's duration is ignored.
    duration: str | None = None
    # Optional override; when set it takes precedence over whatever service
    # name the model extracts from the question. An explicit selection from
    # someone who already knows what they want to investigate is strictly
    # more trustworthy than a guess — but it still goes through the same
    # registry validation as the model's guess would.
    service_hint: str | None = None


class InvestigationPlan(BaseModel):
    intent: Intent
    system_id: str
    system_name: str
    environment: str

    # Already validated against the registry. None means "the whole system".
    service: str | None = None
    namespaces: list[str] = Field(default_factory=list)

    requested_window: TimeWindow
    tools: list[str] = Field(default_factory=list)

    goal: str = ""
    # How the plan was produced, so a degraded run is visible in the output
    # rather than looking like a confident one.
    planner: str = "llm"
    notes: list[str] = Field(default_factory=list)
