apiVersion: v1
kind: Service
metadata:
  name: ollama
  labels:
    app: ollama
spec:
  ports:
  - port: 11434
    name: http
    targetPort: 11434
  selector:
    app: ollama
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ollama
spec:
  serviceName: ollama
  replicas: 0
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest
        resources:
          requests:
            memory: "4Gi"
            cpu: "1000m"
          limits:
            memory: "6Gi"
            cpu: "3000m"
        ports:
        - containerPort: 11434
          name: http
        volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama
      volumes:
      - name: ollama-data
        hostPath:
          path: /mnt/data/ollama
          type: DirectoryOrCreate
