// A horizontal pipeline diagram of the actual backend stages, in the actual
// order they run (see agent/app/pipeline/run.py). Nodes are pending until
// their stage event arrives, pulse while they're the current one, and turn
// green once done — so the flow map isn't decoration, it's a live readout of
// what the agent is doing right now.
const STAGES = [
  { id: 'plan', label: 'Plan', hint: 'Question -> validated investigation plan' },
  { id: 'windows', label: 'Time Window', hint: 'Where the incident actually is, vs. baseline' },
  { id: 'evidence', label: 'Evidence', hint: 'Logs, events and metrics for both windows' },
  { id: 'signals', label: 'Signals', hint: 'Baseline-relative, unit-aware measurements' },
  { id: 'candidates', label: 'Candidates', hint: 'Ranked causes, generated by rules' },
  { id: 'analysis', label: 'LLM Analysis', hint: 'The model picks one candidate and explains it' },
  { id: 'verified', label: 'Verify', hint: 'Citations, support and causal order all checked' },
  { id: 'result', label: 'Report', hint: 'Final narrative, timeline and next steps' },
];

const ICONS = {
  plan: <path d="M9 11l3 3L22 4M21 12v7a2 2 0 01-2 2H5a2 2 0 01-2-2V5a2 2 0 012-2h11" strokeLinecap="round" strokeLinejoin="round" />,
  windows: <><circle cx="12" cy="12" r="9" /><path d="M12 7v5l3 3" strokeLinecap="round" strokeLinejoin="round" /></>,
  evidence: <path d="M4 19.5A2.5 2.5 0 016.5 17H20M4 4.5A2.5 2.5 0 016.5 2H20v20H6.5A2.5 2.5 0 014 19.5v-15z" strokeLinecap="round" strokeLinejoin="round" />,
  signals: <path d="M3 12h4l3 8 4-16 3 8h4" strokeLinecap="round" strokeLinejoin="round" />,
  candidates: <path d="M9 12l2 2 4-4M12 3l8 4-8 4-8-4 8-4zM4 12l8 4 8-4M4 17l8 4 8-4" strokeLinecap="round" strokeLinejoin="round" />,
  analysis: <path d="M12 2a7 7 0 00-4 12.7V17a1 1 0 001 1h6a1 1 0 001-1v-2.3A7 7 0 0012 2zM9 21h6" strokeLinecap="round" strokeLinejoin="round" />,
  verified: <path d="M9 12l2 2 4-4M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" strokeLinecap="round" strokeLinejoin="round" />,
  result: <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8l-6-6zM14 2v6h6M9 13h6M9 17h6M9 9h1" strokeLinecap="round" strokeLinejoin="round" />,
};

function NodeIcon({ id, state }) {
  if (state === 'done') {
    return (
      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
        <path d="M5 13l4 4L19 7" strokeLinecap="round" strokeLinejoin="round" />
      </svg>
    );
  }
  if (state === 'error') {
    return (
      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
        <path d="M12 9v4M12 17h.01M10.3 3.9L2.7 17a2 2 0 001.7 3h15.2a2 2 0 001.7-3L13.7 3.9a2 2 0 00-3.4 0z" strokeLinecap="round" strokeLinejoin="round" />
      </svg>
    );
  }
  return (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
      {ICONS[id]}
    </svg>
  );
}

export default function FlowMap({ stagesData, currentStageId, selectedStageId, onSelect, failedAt }) {
  const currentIndex = STAGES.findIndex((s) => s.id === currentStageId);

  return (
    <div className="li-flowmap" role="list" aria-label="Investigation pipeline">
      {STAGES.map((stage, index) => {
        const hasData = !!stagesData[stage.id];
        const isActive = stage.id === currentStageId;
        const isPast = currentIndex > index;
        const isSelected = selectedStageId === stage.id;
        const isError = failedAt === stage.id;

        let state = 'pending';
        if (isError) state = 'error';
        else if (isActive) state = 'active';
        else if (hasData || isPast) state = 'done';

        return (
          <div className="li-flownode-wrap" key={stage.id}>
            <button
              type="button"
              role="listitem"
              className={`li-flownode li-flownode--${state} ${isSelected ? 'li-flownode--selected' : ''}`}
              disabled={!hasData}
              onClick={() => hasData && onSelect(stage.id)}
              title={stage.hint}
            >
              <span className={`li-flownode-dot li-flownode-dot--${state}`}>
                <NodeIcon id={stage.id} state={state} />
              </span>
              <span className="li-flownode-text">
                <span className="li-flownode-label">{stage.label}</span>
                <span className="li-flownode-hint">
                  {isActive ? 'working…' : isError ? 'failed' : hasData ? 'done' : 'pending'}
                </span>
              </span>
            </button>
            {index < STAGES.length - 1 && (
              <svg className="li-flowarrow" width="20" height="20" viewBox="0 0 24 24" fill="none"
                stroke="currentColor" strokeWidth="2.5">
                <path d="M5 12h13M13 6l6 6-6 6" strokeLinecap="round" strokeLinejoin="round" />
              </svg>
            )}
          </div>
        );
      })}
    </div>
  );
}

export { STAGES };
