#!/usr/bin/env bash
# Bootstraps the LogIntel agent inside WSL: virtualenv, dependencies, and a .env
# whose endpoints are detected for *this* machine rather than hardcoded.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AGENT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)/agent"

say()  { printf '\033[36m%s\033[0m\n' "$*"; }
ok()   { printf '\033[32m[ok]\033[0m %s\n' "$*"; }
warn() { printf '\033[33m[!!]\033[0m %s\n' "$*"; }

# The Windows host as seen from WSL2. Everything on the Windows side — Ollama,
# and the VirtualBox NAT forwards into the VM — lives behind this address, and
# it survives WSL restarts in a way the WSL IP does not.
detect_windows_host() {
  local gw
  gw="$(ip route show default 2>/dev/null | awk '/default/ {print $3; exit}')"
  if [[ -z "${gw}" ]]; then
    gw="$(awk '/nameserver/ {print $2; exit}' /etc/resolv.conf 2>/dev/null || true)"
  fi
  echo "${gw:-172.23.80.1}"
}

probe() {  # probe <url> <label>
  if curl -fsS -m 4 -o /dev/null "$1" 2>/dev/null; then ok "$2 reachable  ($1)"; return 0
  else warn "$2 NOT reachable ($1)"; return 1; fi
}

say "== LogIntel agent bootstrap =="
WINDOWS_HOST="$(detect_windows_host)"
ok "Windows host from WSL: ${WINDOWS_HOST}"

# --- virtualenv ----------------------------------------------------------
command -v python3 >/dev/null || { echo "python3 not found"; exit 1; }
PYV="$(python3 -c 'import sys; print("%d.%d" % sys.version_info[:2])')"
say "Python ${PYV}"
[[ "$(printf '%s\n3.10\n' "${PYV}" | sort -V | head -1)" == "3.10" ]] \
  || { echo "Python 3.10+ required, found ${PYV}"; exit 1; }

if [[ ! -d "${AGENT_DIR}/venv" ]]; then
  say "Creating virtualenv at agent/venv ..."
  python3 -m venv "${AGENT_DIR}/venv"
else
  say "Reusing existing virtualenv at agent/venv"
fi

# shellcheck disable=SC1091
source "${AGENT_DIR}/venv/bin/activate"
python -m pip install --quiet --upgrade pip
say "Installing dependencies ..."
python -m pip install --quiet -r "${AGENT_DIR}/requirements.txt"
ok "dependencies installed"

# --- endpoint detection --------------------------------------------------
say "Probing endpoints ..."
OPENSEARCH_URL="http://localhost:9200"
probe "${OPENSEARCH_URL}" "OpenSearch" || \
  warn "start OpenSearch in WSL and make sure it binds 0.0.0.0"

OLLAMA_URL="http://${WINDOWS_HOST}:11434"
probe "${OLLAMA_URL}/api/tags" "Ollama" || \
  warn "set OLLAMA_HOST=0.0.0.0 on Windows so WSL can reach it"

# Prometheus and the incident controller arrive via the VM's NAT forwards.
PROMETHEUS_URL="http://${WINDOWS_HOST}:30090"
INCIDENTS_URL="http://${WINDOWS_HOST}:30099"
if ! probe "${PROMETHEUS_URL}/-/healthy" "Prometheus (via VM NAT forward)"; then
  if curl -fsS -m 4 -o /dev/null "http://192.168.56.20:30090/-/healthy" 2>/dev/null; then
    PROMETHEUS_URL="http://192.168.56.20:30090"
    INCIDENTS_URL="http://192.168.56.20:30099"
    ok "falling back to the host-only address (192.168.56.20)"
  else
    warn "Prometheus unreachable on both paths — is the VM up? (vagrant status)"
  fi
fi
probe "${INCIDENTS_URL}/incidents" "Incident controller" || true

# --- .env ----------------------------------------------------------------
ENV_FILE="${AGENT_DIR}/.env"
if [[ -f "${ENV_FILE}" ]]; then
  cp "${ENV_FILE}" "${ENV_FILE}.bak"
  warn "existing .env backed up to .env.bak"
fi

cat > "${ENV_FILE}" <<EOF
# Generated by scripts/bootstrap-agent.sh on $(date -Iseconds)
# Re-run that script after a WSL or VM restart to refresh these.

OPENSEARCH_URL=${OPENSEARCH_URL}
OPENSEARCH_USERNAME=
OPENSEARCH_PASSWORD=
OPENSEARCH_VERIFY_SSL=false
OPENSEARCH_LOG_INDEX=logintel-logs-*
OPENSEARCH_EVENT_INDEX=logintel-events-*
OPENSEARCH_INVESTIGATION_INDEX=logintel-investigations

PROMETHEUS_URL=${PROMETHEUS_URL}

OLLAMA_BASE_URL=${OLLAMA_URL}
OLLAMA_MODEL=qwen2.5-coder
OLLAMA_TIMEOUT=180
# num_ctx is the single most important setting here. Ollama defaults to 2048 and
# silently truncates anything longer, discarding the head of the prompt.
OLLAMA_NUM_CTX=16384
OLLAMA_TEMPERATURE=0
OLLAMA_SEED=42

INCIDENT_CONTROLLER_URL=${INCIDENTS_URL}
LOG_LEVEL=INFO
EOF

ok "wrote ${ENV_FILE}"

# --- index templates -----------------------------------------------------
# Applied before the testbed ever writes a document. If OpenSearch creates these
# indices dynamically first, `system.id` becomes a text field and every term
# filter in the pipeline silently matches nothing — a failure that looks exactly
# like a healthy system with no logs.
say "Applying index templates ..."
( cd "${AGENT_DIR}" && python - <<'PY'
import asyncio
from app.sources.opensearch import OpenSearchClient

async def main():
    client = OpenSearchClient()
    try:
        applied = await client.ensure_templates()
        print(f"  applied: {', '.join(applied)}")
        for problem in await client.check_mapping_conflicts():
            print(f"  WARNING: {problem}")
    finally:
        await client.close()

try:
    asyncio.run(main())
except Exception as exc:
    print(f"  could not apply templates: {exc}")
    print("  start OpenSearch and re-run this script BEFORE bringing the testbed up")
PY
) || warn "template application failed; see above"

echo
say "Next:"
echo "  cd ${AGENT_DIR}"
echo "  source venv/bin/activate"
echo "  uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
echo
echo "  then: curl -s localhost:8000/api/health | python3 -m json.tool"
